[server_configure]
server_addr = ":8088"

[qianfan_configure]
api_key = ""
secret_key = ""
app_builder_key = ""
aojiao_appid = "e566ffdb-bb7f-445a-b0b7-6bd805e3abd1"
normal_appid = "7f9db346-f12c-4e2e-971c-9c6ac95fb7bc"

[redis_configure]
host = "127.0.0.1"
port = "6379"

[mysql_configure]
driver = "mysql"
user_name = ""
pw = ""
host = "127.0.0.1"
port = "3306"
dbname = "wx_robot"
timeout = "10s"

[log_configure]
log_file_path = "../log/"
log_file_name = "system.log"

[sign_configure]
sign_reward_first = 200
sign_reward_second = 150
sign_reward_third = 100
sign_reward_else = 50

[file_configure]
holiday_file = "../file/holiday"
img_file = "../file/img/"
ele_poster_file = "../file/ele.jpg"

[corn_task_configure]
holiday_tips = "0 10 10 * *"
news_tips = "0 0 15 * *"
regular_update = "0 0 23 * *"

[tx_configure]
secret_id = ""
secret_key = ""
